# Capítulo 9 - NumPy (Numerial Python)

## NumPy

In [1]:
import numpy as dsa

In [2]:
dsa.__version__

'1.26.4'

## Criando Arrays NumPy

In [3]:
arrl = dsa.array([10,21,32,43,48,15,76,57,89])

In [4]:
print(arrl)

[10 21 32 43 48 15 76 57 89]


In [5]:
type(arrl)

numpy.ndarray

In [6]:
arrl.shape

(9,)

## Indexação em Arrays NumPy

In [10]:
print(arrl)

[10 21 32 43 48 15 76 57 89]


In [11]:
arrl[4]

48

In [12]:
arrl[1:4]

array([21, 32, 43])

In [13]:
arrl[1:4+1]

array([21, 32, 43, 48])

In [14]:
indices = [1,2,5,6]

In [15]:
arrl[indices]

array([21, 32, 15, 76])

In [16]:
mask = (arrl % 2 == 0)

In [17]:
arrl[mask]

array([10, 32, 48, 76])

In [18]:
arrl[0] = 100

In [19]:
print(arrl)

[100  21  32  43  48  15  76  57  89]


In [20]:
try:
    arrl[0] = 'Novo elemento'
except:
    print("Operação não permitida")

Operação não permitida


## Funções NumPy

In [21]:
arr2 = dsa.array([1,2,3,4,5])

In [22]:
print(arr2)

[1 2 3 4 5]


In [23]:
type(arr2)

numpy.ndarray

In [37]:
arr2

array([1, 2, 3, 4, 5])

In [38]:
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [39]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [28]:
dsa

<module 'numpy' from '/Users/vitorsainvallio/Library/Mobile Documents/com~apple~CloudDocs/PROJETOS/DSA/Python DSA /.venv/lib/python3.9/site-packages/numpy/__init__.py'>

In [40]:
arr3 = dsa.arange(0,50,5)

In [41]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [42]:
type(arr3)

numpy.ndarray

In [43]:
dsa.shape(arr3)

(10,)

In [44]:
print(arr3.dtype)

int64


In [34]:
arr4 = dsa.zeros(10)

In [68]:
print(arr4)
print(arr4.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [49]:
arr5 = dsa.eye(3)

In [69]:
print(arr5)
print(arr5.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64


In [51]:
arr6 = dsa.diag(dsa.array([1,2,3,4]))

In [70]:
print(arr6)
print(arr6.dtype)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
int64


In [64]:
arr7 = dsa.array([True, False, False, True])

In [71]:
print(arr7)
print(arr7.dtype)

[ True False False  True]
bool


In [66]:
arr8 = dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [72]:
print(arr8)
print(arr8.dtype)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']
<U16


In [59]:
print(dsa.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [60]:
print(dsa.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [74]:
print(dsa.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


## Manipulando Matrizes

In [62]:
arr9 = dsa.array([[1,2,3],[4,5,6]])

In [76]:
type(arr9)

numpy.ndarray

In [77]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [78]:
print(arr9.shape)

(2, 3)


In [80]:
arr10 = dsa.ones((2,3))

In [81]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [82]:
lista = [[13,81,22], [0,34,59], [21,48,94]]

In [83]:
arr11 = dsa.matrix(lista)

In [84]:
type(arr11)

numpy.matrix

In [85]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [87]:
dsa.shape(arr11)

(3, 3)

In [88]:
arr11.size

9

In [89]:
print(arr11.dtype)

int64


In [90]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [91]:
arr11[2,1]

48

In [92]:
arr11[0:2,2]

matrix([[22],
        [59]])

In [93]:
arr11[1,]

matrix([[ 0, 34, 59]])

In [94]:
arr11[1,0] = 100